name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_Linux-64bit.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name 'syedhaiderkarrar'
          git config user.email 'syedhaiderkarrar@live.com'
          cd public
          git init
          git add .
          git commit -m 'Updated site'
          git push https://syedhaiderkarrar:${{ secrets.PAT_TOKEN }}@github.com/binaridigital/binaryblocks.git HEAD:gh-pages
